### ISSUE TITLE
Editing filter while it is disabled enables the filter but the result does not change

### ISSUE THREAD

**Issue by danandrei** [jillix/bind-filter#27]

**Comment by gabipetrovay** [comment]
@silviubogan can you please look over this problem?

**Comment by gabipetrovay** [comment]
To reproduce:

0. You have a template with N items.
1. Make a filter on a template that reduces the results to X < N.
2. Disable the filter (eye icon) and the N results are shown back.
3. Edit the filter while disabled and put an aberrant value that you know would find nothing.
4. Saving the filter enables it back and you see the problem: the table shows again the X results instead of 0.

Possible solutions:

A. Saving the filter also updates the query not only the UI.
B. Saving a disabled filter does not enable it back.

I would solve both A and B.

**Comment by silviubogan** [comment]
@gabipetrovay @danandrei, I opened the #28 pull request and I solved both solutions.

**Comment by gabipetrovay** [comment]
I've merge pull request #28
